spring:
  application:
    name: spring-api

  datasource:
    url: jdbc:mysql://localhost:3306/api_database
    username: root
    password: Krish@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        use_sql_comments: false
#  mail services

# App name: SpringApi
# Your app password for your device: hgxk svcy tjzy tout 
# How to use it
# Go to the settings for your Google Account in the application or device you are trying to set up. 
# Replace your password with the 16-character password shown above.
# Just like your normal password, this app password grants complete access 
# to your Google Account. You won't need to remember it, so don't write it down or share it with anyone.
# This is the reference doc
#  https://medium.com/@seonggil/send-email-with-spring-boot-and-gmail-27c14fc3d859
  mail:
    host: smtp.gmail.com
    port: 587
    username: springboot0034@gmail.com
    password: hgxk svcy tjzy tout 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt-secret-key: z7Dtg9fCxpnPZYvkIdpm2zD28wbOr836oOTZ5UdMwlo=


server:
  port: 9090
twilio:
  account-sid: AC5ade1a726c55a4e4f0560b9b4e53fd05
  auth-token: 68b6416b05175825b309d4d6d2f67dc4
  trial-number: +14157277298



# jwt:
  # Add your JWT properties here if needed

# Twilio: ####
#  username: springboot0034@gmail.com
#  password: SPRingboot@003400
# ##### Recovery code #######
# If you lose your phone, or don’t have access to your verification device, this code is your failsafe to access your account.
# UMX93FUW6NPD8YAGDLRS4RE7

#  ####Account Info ####
#  Account SID:  AC5ade1a726c55a4e4f0560b9b4e53fd05
#  Auth Token: 68b6416b05175825b309d4d6d2f67dc4

#  Create new Service
# Friendly name: Verification Code
#  Service SID: VAdd7bbdde7933bbe41b28785e36c4a751